// This file is generated by Slice Machine. Update with care!

import Example from './Example';
import Features from './Features';
import Hero from './Hero';
import ImageAndText from './ImageAndText';

export {
	Example,
	Features,
	Hero,
	ImageAndText,
};

export const components = {
	example: Example,
	features: Features,
	hero: Hero,
	image_and_text: ImageAndText,
};
