import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import "./globals.css";
import Head from "next/head"

import NavBar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head  >
        <ThemeModeScript />        
      </head>
      
      <body className='dark:bg-[#e6dec7] dark:text-[#5f4a37] ' >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
